/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'MCP Server adapter settings': {
        'en': 'MCP Server adapter settings',
        'de': 'MCP-Server Adaptereinstellungen',
        'ru': 'Настройки адаптера MCP Server',
        'pt': 'Configurações do adaptador MCP Server',
        'nl': 'MCP Server adapter instellingen',
        'fr': 'Paramètres de l\'adaptateur MCP Server',
        'it': 'Impostazioni dell\'adattatore MCP Server',
        'es': 'Configuración del adaptador MCP Server',
        'pl': 'Ustawienia adaptera MCP Server',
        'zh-cn': 'MCP服务器适配器设置'
    },
    'Server Configuration': {
        'en': 'Server Configuration',
        'de': 'Server-Konfiguration',
        'ru': 'Конфигурация сервера',
        'pt': 'Configuração do servidor',
        'nl': 'Server configuratie',
        'fr': 'Configuration du serveur',
        'it': 'Configurazione del server',
        'es': 'Configuración del servidor',
        'pl': 'Konfiguracja serwera',
        'zh-cn': '服务器配置'
    },
    'Server Port': {
        'en': 'Server Port',
        'de': 'Server-Port',
        'ru': 'Порт сервера',
        'pt': 'Porta do servidor',
        'nl': 'Server poort',
        'fr': 'Port du serveur',
        'it': 'Porta del server',
        'es': 'Puerto del servidor',
        'pl': 'Port serwera',
        'zh-cn': '服务器端口'
    },
    'Port for the MCP server (default: 8932)': {
        'en': 'Port for the MCP server (default: 8932)',
        'de': 'Port für den MCP-Server (Standard: 8932)',
        'ru': 'Порт для MCP сервера (по умолчанию: 8932)',
        'pt': 'Porta para o servidor MCP (padrão: 8932)',
        'nl': 'Poort voor de MCP server (standaard: 8932)',
        'fr': 'Port pour le serveur MCP (par défaut: 8932)',
        'it': 'Porta per il server MCP (predefinito: 8932)',
        'es': 'Puerto para el servidor MCP (predeterminado: 8932)',
        'pl': 'Port dla serwera MCP (domyślnie: 8932)',
        'zh-cn': 'MCP服务器端口（默认：8932）'
    },
    'Proxy Configuration': {
        'en': 'Proxy Configuration',
        'de': 'Proxy-Konfiguration',
        'ru': 'Конфигурация прокси',
        'pt': 'Configuração do proxy',
        'nl': 'Proxy configuratie',
        'fr': 'Configuration du proxy',
        'it': 'Configurazione del proxy',
        'es': 'Configuración del proxy',
        'pl': 'Konfiguracja proxy',
        'zh-cn': '代理配置'
    },
    'Enable MCP Proxy': {
        'en': 'Enable MCP Proxy',
        'de': 'MCP-Proxy aktivieren',
        'ru': 'Включить MCP прокси',
        'pt': 'Ativar proxy MCP',
        'nl': 'MCP proxy inschakelen',
        'fr': 'Activer le proxy MCP',
        'it': 'Abilita proxy MCP',
        'es': 'Habilitar proxy MCP',
        'pl': 'Włącz proxy MCP',
        'zh-cn': '启用MCP代理'
    },
    'Proxy Port': {
        'en': 'Proxy Port',
        'de': 'Proxy-Port',
        'ru': 'Порт прокси',
        'pt': 'Porta do proxy',
        'nl': 'Proxy poort',
        'fr': 'Port du proxy',
        'it': 'Porta del proxy',
        'es': 'Puerto del proxy',
        'pl': 'Port proxy',
        'zh-cn': '代理端口'
    },
    'Port for the MCP proxy (default: 8933)': {
        'en': 'Port for the MCP proxy (default: 8933)',
        'de': 'Port für den MCP-Proxy (Standard: 8933)',
        'ru': 'Порт для MCP прокси (по умолчанию: 8933)',
        'pt': 'Porta para o proxy MCP (padrão: 8933)',
        'nl': 'Poort voor de MCP proxy (standaard: 8933)',
        'fr': 'Port pour le proxy MCP (par défaut: 8933)',
        'it': 'Porta per il proxy MCP (predefinito: 8933)',
        'es': 'Puerto para el proxy MCP (predeterminado: 8933)',
        'pl': 'Port dla proxy MCP (domyślnie: 8933)',
        'zh-cn': 'MCP代理端口（默认：8933）'
    },
    'Authentication': {
        'en': 'Authentication',
        'de': 'Authentifizierung',
        'ru': 'Аутентификация',
        'pt': 'Autenticação',
        'nl': 'Authenticatie',
        'fr': 'Authentification',
        'it': 'Autenticazione',
        'es': 'Autenticación',
        'pl': 'Uwierzytelnianie',
        'zh-cn': '身份验证'
    },
    'Enable Authentication': {
        'en': 'Enable Authentication',
        'de': 'Authentifizierung aktivieren',
        'ru': 'Включить аутентификацию',
        'pt': 'Ativar autenticação',
        'nl': 'Authenticatie inschakelen',
        'fr': 'Activer l\'authentification',
        'it': 'Abilita autenticazione',
        'es': 'Habilitar autenticación',
        'pl': 'Włącz uwierzytelnianie',
        'zh-cn': '启用身份验证'
    },
    'API Key': {
        'en': 'API Key',
        'de': 'API-Schlüssel',
        'ru': 'API ключ',
        'pt': 'Chave API',
        'nl': 'API sleutel',
        'fr': 'Clé API',
        'it': 'Chiave API',
        'es': 'Clave API',
        'pl': 'Klucz API',
        'zh-cn': 'API密钥'
    },
    'API key for authentication (leave empty to generate)': {
        'en': 'API key for authentication (leave empty to generate)',
        'de': 'API-Schlüssel für Authentifizierung (leer lassen zum Generieren)',
        'ru': 'API ключ для аутентификации (оставьте пустым для генерации)',
        'pt': 'Chave API para autenticação (deixe vazio para gerar)',
        'nl': 'API sleutel voor authenticatie (leeg laten om te genereren)',
        'fr': 'Clé API pour l\'authentification (laisser vide pour générer)',
        'it': 'Chiave API per l\'autenticazione (lasciare vuoto per generare)',
        'es': 'Clave API para autenticación (dejar vacío para generar)',
        'pl': 'Klucz API do uwierzytelniania (pozostaw pusty, aby wygenerować)',
        'zh-cn': '用于身份验证的API密钥（留空以生成）'
    },
    'Enabled Tools': {
        'en': 'Enabled Tools',
        'de': 'Aktivierte Tools',
        'ru': 'Включенные инструменты',
        'pt': 'Ferramentas ativadas',
        'nl': 'Ingeschakelde tools',
        'fr': 'Outils activés',
        'it': 'Strumenti abilitati',
        'es': 'Herramientas habilitadas',
        'pl': 'Włączone narzędzia',
        'zh-cn': '启用的工具'
    },
    'State Management': {
        'en': 'State Management',
        'de': 'Zustandsverwaltung',
        'ru': 'Управление состояниями',
        'pt': 'Gerenciamento de estados',
        'nl': 'Status beheer',
        'fr': 'Gestion des états',
        'it': 'Gestione degli stati',
        'es': 'Gestión de estados',
        'pl': 'Zarządzanie stanami',
        'zh-cn': '状态管理'
    },
    'Object Management': {
        'en': 'Object Management',
        'de': 'Objektverwaltung',
        'ru': 'Управление объектами',
        'pt': 'Gerenciamento de objetos',
        'nl': 'Object beheer',
        'fr': 'Gestion des objets',
        'it': 'Gestione degli oggetti',
        'es': 'Gestión de objetos',
        'pl': 'Zarządzanie obiektami',
        'zh-cn': '对象管理'
    },
    'Adapter Control': {
        'en': 'Adapter Control',
        'de': 'Adaptersteuerung',
        'ru': 'Управление адаптерами',
        'pt': 'Controle de adaptadores',
        'nl': 'Adapter controle',
        'fr': 'Contrôle des adaptateurs',
        'it': 'Controllo degli adattatori',
        'es': 'Control de adaptadores',
        'pl': 'Kontrola adapterów',
        'zh-cn': '适配器控制'
    },
    'System Information': {
        'en': 'System Information',
        'de': 'Systeminformationen',
        'ru': 'Системная информация',
        'pt': 'Informações do sistema',
        'nl': 'Systeem informatie',
        'fr': 'Informations système',
        'it': 'Informazioni di sistema',
        'es': 'Información del sistema',
        'pl': 'Informacje systemowe',
        'zh-cn': '系统信息'
    },
    'Filters': {
        'en': 'Filters',
        'de': 'Filter',
        'ru': 'Фильтры',
        'pt': 'Filtros',
        'nl': 'Filters',
        'fr': 'Filtres',
        'it': 'Filtri',
        'es': 'Filtros',
        'pl': 'Filtry',
        'zh-cn': '过滤器'
    },
    'State Filter (Regex)': {
        'en': 'State Filter (Regex)',
        'de': 'Zustandsfilter (Regex)',
        'ru': 'Фильтр состояний (Regex)',
        'pt': 'Filtro de estados (Regex)',
        'nl': 'Status filter (Regex)',
        'fr': 'Filtre d\'états (Regex)',
        'it': 'Filtro stati (Regex)',
        'es': 'Filtro de estados (Regex)',
        'pl': 'Filtr stanów (Regex)',
        'zh-cn': '状态过滤器（正则表达式）'
    },
    'Regular expression to filter accessible states': {
        'en': 'Regular expression to filter accessible states',
        'de': 'Regulärer Ausdruck zum Filtern zugänglicher Zustände',
        'ru': 'Регулярное выражение для фильтрации доступных состояний',
        'pt': 'Expressão regular para filtrar estados acessíveis',
        'nl': 'Reguliere expressie om toegankelijke statussen te filteren',
        'fr': 'Expression régulière pour filtrer les états accessibles',
        'it': 'Espressione regolare per filtrare gli stati accessibili',
        'es': 'Expresión regular para filtrar estados accesibles',
        'pl': 'Wyrażenie regularne do filtrowania dostępnych stanów',
        'zh-cn': '用于过滤可访问状态的正则表达式'
    },
    'Object Filter (Regex)': {
        'en': 'Object Filter (Regex)',
        'de': 'Objektfilter (Regex)',
        'ru': 'Фильтр объектов (Regex)',
        'pt': 'Filtro de objetos (Regex)',
        'nl': 'Object filter (Regex)',
        'fr': 'Filtre d\'objets (Regex)',
        'it': 'Filtro oggetti (Regex)',
        'es': 'Filtro de objetos (Regex)',
        'pl': 'Filtr obiektów (Regex)',
        'zh-cn': '对象过滤器（正则表达式）'
    },
    'Regular expression to filter accessible objects': {
        'en': 'Regular expression to filter accessible objects',
        'de': 'Regulärer Ausdruck zum Filtern zugänglicher Objekte',
        'ru': 'Регулярное выражение для фильтрации доступных объектов',
        'pt': 'Expressão regular para filtrar objetos acessíveis',
        'nl': 'Reguliere expressie om toegankelijke objecten te filteren',
        'fr': 'Expression régulière pour filtrer les objets accessibles',
        'it': 'Espressione regolare per filtrare gli oggetti accessibili',
        'es': 'Expresión regular para filtrar objetos accesibles',
        'pl': 'Wyrażenie regularne do filtrowania dostępnych obiektów',
        'zh-cn': '用于过滤可访问对象的正则表达式'
    },
    'Advanced Settings': {
        'en': 'Advanced Settings',
        'de': 'Erweiterte Einstellungen',
        'ru': 'Расширенные настройки',
        'pt': 'Configurações avançadas',
        'nl': 'Geavanceerde instellingen',
        'fr': 'Paramètres avancés',
        'it': 'Impostazioni avanzate',
        'es': 'Configuración avanzada',
        'pl': 'Ustawienia zaawansowane',
        'zh-cn': '高级设置'
    },
    'Max Results': {
        'en': 'Max Results',
        'de': 'Max. Ergebnisse',
        'ru': 'Макс. результатов',
        'pt': 'Máx. resultados',
        'nl': 'Max. resultaten',
        'fr': 'Max. résultats',
        'it': 'Max. risultati',
        'es': 'Máx. resultados',
        'pl': 'Maks. wyników',
        'zh-cn': '最大结果数'
    },
    'Maximum number of results per query': {
        'en': 'Maximum number of results per query',
        'de': 'Maximale Anzahl von Ergebnissen pro Abfrage',
        'ru': 'Максимальное количество результатов на запрос',
        'pt': 'Número máximo de resultados por consulta',
        'nl': 'Maximaal aantal resultaten per query',
        'fr': 'Nombre maximum de résultats par requête',
        'it': 'Numero massimo di risultati per query',
        'es': 'Número máximo de resultados por consulta',
        'pl': 'Maksymalna liczba wyników na zapytanie',
        'zh-cn': '每次查询的最大结果数'
    },
    'Enable Debug Logging': {
        'en': 'Enable Debug Logging',
        'de': 'Debug-Protokollierung aktivieren',
        'ru': 'Включить отладочное логирование',
        'pt': 'Ativar log de depuração',
        'nl': 'Debug logging inschakelen',
        'fr': 'Activer la journalisation de débogage',
        'it': 'Abilita registrazione debug',
        'es': 'Habilitar registro de depuración',
        'pl': 'Włącz logowanie debugowania',
        'zh-cn': '启用调试日志'
    },
    'Log Level': {
        'en': 'Log Level',
        'de': 'Protokollebene',
        'ru': 'Уровень логирования',
        'pt': 'Nível de log',
        'nl': 'Log niveau',
        'fr': 'Niveau de journalisation',
        'it': 'Livello di log',
        'es': 'Nivel de registro',
        'pl': 'Poziom logowania',
        'zh-cn': '日志级别'
    },
    'Error': {
        'en': 'Error',
        'de': 'Fehler',
        'ru': 'Ошибка',
        'pt': 'Erro',
        'nl': 'Fout',
        'fr': 'Erreur',
        'it': 'Errore',
        'es': 'Error',
        'pl': 'Błąd',
        'zh-cn': '错误'
    },
    'Warning': {
        'en': 'Warning',
        'de': 'Warnung',
        'ru': 'Предупреждение',
        'pt': 'Aviso',
        'nl': 'Waarschuwing',
        'fr': 'Avertissement',
        'it': 'Avviso',
        'es': 'Advertencia',
        'pl': 'Ostrzeżenie',
        'zh-cn': '警告'
    },
    'Info': {
        'en': 'Info',
        'de': 'Info',
        'ru': 'Информация',
        'pt': 'Informação',
        'nl': 'Info',
        'fr': 'Info',
        'it': 'Info',
        'es': 'Información',
        'pl': 'Informacja',
        'zh-cn': '信息'
    },
    'Debug': {
        'en': 'Debug',
        'de': 'Debug',
        'ru': 'Отладка',
        'pt': 'Depuração',
        'nl': 'Debug',
        'fr': 'Débogage',
        'it': 'Debug',
        'es': 'Depuración',
        'pl': 'Debugowanie',
        'zh-cn': '调试'
    }
}; 